version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      worker-button:
        condition: service_started
      worker-price:
        condition: service_started
      fastapi_app:
        condition: service_started
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      redis-commander:
        condition: service_healthy
    networks:
      - semyon-network

  worker-button:
    build: ./apps
    env_file:
      - ./apps/.env
      - ./apps/.env.celery
    depends_on:
      fastapi_app:
        condition: service_started
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      redis-commander:
        condition: service_healthy
    networks:
      - semyon-network
    command: celery -A apps.src.task_queue.celery_setup:celery_app worker -Q button --loglevel=INFO --hostname=button@%h -n button_worker

  worker-price:
    build: ./apps
    env_file:
      - ./apps/.env
      - ./apps/.env.celery
    depends_on:
      fastapi_app:
        condition: service_started
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      redis-commander:
        condition: service_healthy
    networks:
      - semyon-network
    command: celery -A apps.src.task_queue.celery_setup:celery_app worker -Q price --loglevel=INFO --hostname=price@%h -n price_worker

  fastapi_app:
    build: ./apps
    env_file:
      - ./apps/.env
      - ./apps/.env.celery
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      redis-commander:
        condition: service_healthy
    ports:
      - 8000:8000
    networks:
      - semyon-network
    command:
      - sh
      - -c
      - |
        alembic -c /my_project/apps/alembic.ini upgrade head
        gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - semyon-network

  redis:
    image: redis:6.2-alpine
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    ports:
      - 6379:6379
    networks:
      - semyon-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - semyon-network

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.postgres
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "ab_exp_db", "-U", "ab_exp_user" ]
    networks:
      - semyon-network

volumes:
  postgres_data:
  rabbitmq_data:
networks:
  semyon-network:
    driver: bridge
